//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwiftyNames.V1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDetail
    {
        public int InfoId { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string SessionKey { get; set; }
        public int NewsPaperId { get; set; }
        public int DayId { get; set; }
        public System.DateTime Date { get; set; }
        public string OldFullName { get; set; }
        public string NewFullName { get; set; }
    }
}
