//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwiftyNames.V1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsPapersPrice
    {
        public NewsPapersPrice()
        {
            this.Forms = new HashSet<Form>();
        }
    
        public int Id { get; set; }
        public string NewsPaper { get; set; }
        public string PaperImage { get; set; }
        public string PriceTag { get; set; }
        public string PaperSlogan { get; set; }
        public string NoticePrice { get; set; }
    
        public virtual ICollection<Form> Forms { get; set; }
    }
}
