//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwiftyNames.V1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicNotice
    {
        public int NoticeId { get; set; }
        public string NoticeEmail { get; set; }
        public string NoticePhone { get; set; }
        public string NoticeWord { get; set; }
        public string NoticeName { get; set; }
        public int NoticeDayId { get; set; }
        public System.DateTime NoticeDate { get; set; }
        public int NoticePaperId { get; set; }
    }
}
