//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwiftyNames.V1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upload
    {
        public int UploadId { get; set; }
        public string SessionKey { get; set; }
        public string NameOfFile { get; set; }
        public string IdentityFile { get; set; }
    }
}
